apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-cfg
  namespace: mongo
data:
  haproxy.conf: |
    global
      daemon
      maxconn 4096

    defaults
      mode http
      balance leastconn
      retries 3
      option httpchk GET /health HTTP/1.0\r\nHost:\ app.example.com
      option http-server-close
      option dontlognull
      timeout connect   300ms
      timeout check    1000ms
      timeout client  30000ms
      timeout server  30000ms

    #Load balancer stats page access at hostname:8000/haproxy_stats
    frontend stats
        bind *:8000
        mode http
        option httplog
        log global
        stats enable
        stats realm Haproxy\ Statistics 
        stats uri /haproxy_stats
        stats hide-version
        stats auth admin:admin@rserve

    frontend mongos
        bind *:27000 accept-proxy
        mode tcp
        option tcplog
        timeout client  1m
        default_backend mongos_backend

    backend mongos_backend
        mode tcp
        option tcplog
        option log-health-checks
        balance roundrobin
        timeout connect 10s
        timeout server 1m   
        server mongos1 mongos-0.mongo:27017 check inter 2s

    frontend master_sh0
        bind *:27001 accept-proxy
        mode tcp
        option tcplog
        timeout client 1m
        default_backend master_sh0_backend

    frontend master_sh1
        bind *:27002 accept-proxy
        mode tcp
        option tcplog
        timeout client 1m
        default_backend master_sh1_backend

    backend master_sh0_backend
        mode tcp
        option tcplog
        option log-health-checks
        balance roundrobin
        timeout connect 10s
        timeout server 1m   
        server master1 mongodb-sh0-0.mongo:27017 check inter 2s

    backend master_sh1_backend
        mode tcp
        option tcplog
        option log-health-checks
        balance roundrobin
        timeout connect 10s
        timeout server 1m   
        server master1 mongodb-sh1-0.mongo:27017 check inter 2s

    frontend rserve_frontend
        bind *:27017 accept-proxy
        mode tcp
        option tcplog
        timeout client 1m
        default_backend rserve_backend

    backend rserve_backend
        mode tcp
        option tcplog
        option log-health-checks
        balance roundrobin
        option redispatch 2
        timeout connect 10s
        timeout server 1m
        server sh0-1 mongodb-sh0-1.mongo:27017 check inter 2s
        server sh0-2 mongodb-sh0-2.mongo:27017 check inter 2s
        server sh1-0 mongodb-sh1-1.mongo:27017 check inter 2s
        server sh1-1 mongodb-sh1-2.mongo:27017 check inter 2s
---
kind: Service
apiVersion: v1
metadata:
  name: haproxy-service
  namespace: mongo
spec:
  selector:
    app: haproxy
  ports:
    - name: http
      protocol: TCP
      port: 8000
      nodePort: 31080
    - name: mongos
      protocol: TCP
      port: 27000
      nodePort: 32000
    - name: mongo-read
      protocol: TCP
      port: 27017
      nodePort: 31017
    - name: mongo-master-sh0
      protocol: TCP
      port: 27001
      nodePort: 32001
    - name: mongo-master-sh1
      protocol: TCP
      port: 27002
      nodePort: 32002
  type: LoadBalancer # NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:2.6.14
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: haproxy-conf
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: haproxy-conf
          configMap:
            name: haproxy-cfg
            items:
              - key: haproxy.conf
                path: haproxy.cfg
